fix: multibase in pubsub http rpc  interop tests
ipfs/interop pull request #387
Opened 2021-10-21 11:23 UTC by lidel

This PR updates `pubsub`  interop tests with  HTTP RPC wire format changes introduced in https://github.com/ipfs/js-ipfs/pull/3922 and   https://github.com/ipfs/go-ipfs/pull/8183 and runs against the code from mentioned PRs (js-ipfs from https://github.com/ipfs/js-ipfs/pull/3922 + go-ipfs 0.11.0-rc1) to ensure things work end-to-end.

## TODO
- [x] use js-ipfs and js-ipfs-http-client from https://github.com/ipfs/js-ipfs/pull/3922
- [x] use go-ipfs from https://github.com/ipfs/go-ipfs/pull/8183
- [x] make CI green with existing tests
- [x] update pubsub tests to use topic and data payload with `\n` to safeguard against regressions described in https://github.com/ipfs/go-ipfs/issues/7939
- [x] remove `http-rpc-runtime` or refactor it to be useful outside of this PR. The Rube Goldberg machine for testing HTTP RPC wire format change end-to-end
    it should be removed after:
  - [ ] js-ipfs release ships with necessary changes
  - [x] go-ipfs ships with necessary changes
- [x] rebase and restore tests skipped in https://github.com/ipfs/interop/pull/388

2021-11-08 11:39 UTC, achingbrain commented on .gitignore
> +tmp
It looks like all the work happens in `/tmp` so is this ignore necessary?

2021-11-08 11:40 UTC, achingbrain commented on test/pubsub.js
>        it('should exchange non ascii data', function () {
Maybe the changes here should be a separate test?

2021-11-08 11:41 UTC, achingbrain commented on test/pubsub.js
> +        const topic = 'pubsub\nbinary\n'
Same, this should be a separate test - we are testing binary data here, not newlines in topic names.

2021-11-08 11:41 UTC, achingbrain requested changes
LGTM, just a few small things in the comments that need addressing.

2021-11-17 23:15 UTC, lidel commented
Rebased on top of #397

2021-11-29 21:32 UTC, lidel commented on scripts/custom-runtime.sh
> +            git checkout 153697d524f449ee9bec97245b0fcd7ebc2e8170
Switching to master in prep for https://github.com/ipfs/go-ipfs/pull/8183 to land.
```suggestion
        git clone https://github.com/ipfs/go-ipfs.git
        cd go-ipfs
            # implementation from https://github.com/ipfs/go-ipfs/pull/8183
            git switch master
```

2021-12-07 14:51 UTC, lidel commented
Continued in https://github.com/ipfs/interop/pull/410

2021-12-07 14:51 UTC, closed without merging